on:
  pull_request:
    branches:
      - testing
      - master
  push:
    branches:
      - testing
      - master
name: "Build & Release"
jobs:
  build:
    permissions: write-all
    name: Build & Release
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.12'
          channel : 'stable'
      - run: flutter pub get

      - run: flutter build
      - run: flutter build appbundle

      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/debug/*,build/ios/iphoneos/app.ipa"
          tag: v1.0.${{ github.run_number }}
          
          
